#pragma once

#include <cstdint>

namespace v2::core {

enum class FailLabel : std::uint16_t {
    AERO_SOLIDITY_FAIL,
    AERO_TIPMACH_FAIL,
    AERO_DISK_LOADING_FAIL,
    AERO_BEMT_DIVERGENCE,
    ELEC_MOTOR_CURRENT_FAIL,
    ELEC_MOTOR_THERMAL_FAIL,
    ELEC_ESC_THERMAL_FAIL,
    ELEC_BUS_CURRENT_FAIL,
    ELEC_BATTERY_INFEASIBLE,
    ELEC_BATTERY_THERMAL_FAIL,
    ENERGY_ENDURANCE_FAIL,
    ENERGY_NEGATIVE_MARGIN,
    STRUCT_STRESS_FAIL,
    STRUCT_BUCKLING_FAIL,
    STRUCT_FATIGUE_FAIL,
    SYS_CONVERGENCE_FAIL,
    SYS_NAN_FAIL,
    SYS_INFEASIBLE
};

}  // namespace v2::core
