"""Tests for v2.python.ai.engineering_ai — local engineering knowledge engine."""

from pathlib import Path

from v2.python.ai import (
    EngineeringKnowledgeBase,
    EngineeringQueryEngine,
    KnowledgeChunk,
    QueryResult,
)
from v2.python.ai.engineering_ai import (
    ConversationContext,
    ConversationTurn,
    classify_intent,
)
from v2.python.ai.memory import MemoryStore

# ── KnowledgeChunk ───────────────────────────────────────────────────────


def test_knowledge_chunk_creation() -> None:
    chunk = KnowledgeChunk(
        text="Lift = 0.5 * rho * V^2 * S * CL",
        source="aerospace_math.md",
        heading="Lift Equation",
        domain="aerospace",
    )
    assert chunk.domain == "aerospace"
    assert "Lift" in chunk.text


# ── EngineeringKnowledgeBase ────────────────────────────────────────────


def test_knowledge_base_from_texts() -> None:
    kb = EngineeringKnowledgeBase.from_texts(
        [
            "Drag coefficient increases with angle of attack.",
            "Ohm's law: V = I * R for resistive circuits.",
            "Thermal conductivity determines heat transfer rate.",
        ],
        source="test",
        domain="general",
    )
    assert len(kb.chunks) == 3


def test_knowledge_base_search_returns_relevant() -> None:
    kb = EngineeringKnowledgeBase.from_texts(
        [
            "Lift is generated by pressure difference across an airfoil.",
            "Ohm's law relates voltage, current, and resistance.",
            "Thrust-to-weight ratio determines climb capability.",
        ],
        domain="engineering",
    )
    results = kb.search("airfoil lift pressure", top_k=2)
    assert len(results) >= 1
    assert results[0].chunk.text.startswith("Lift")


def test_knowledge_base_search_empty_query() -> None:
    kb = EngineeringKnowledgeBase.from_texts(["Some text."])
    assert kb.search("") == []
    assert kb.search("   ") == []


def test_knowledge_base_search_no_match() -> None:
    kb = EngineeringKnowledgeBase.from_texts(["alpha beta gamma"])
    results = kb.search("zzzzzzzzz")
    assert results == []


def test_knowledge_base_domain_filter() -> None:
    kb = EngineeringKnowledgeBase()
    kb.chunks = [
        KnowledgeChunk(text="Lift force equation", source="a.md", heading="h", domain="aero"),
        KnowledgeChunk(text="Ohm law equation", source="b.md", heading="h", domain="circuits"),
    ]
    kb._build_index()
    results = kb.search("equation", domain_filter="aero")
    assert all("aero" in r.chunk.domain for r in results)


def test_knowledge_base_domains_property() -> None:
    kb = EngineeringKnowledgeBase.from_texts(
        ["a", "b", "c"], domain="thermal",
    )
    assert "thermal" in kb.domains


def test_knowledge_base_from_directory(tmp_path: Path) -> None:
    """Load from a directory with real markdown files."""
    md1 = tmp_path / "aero_math.md"
    md1.write_text(
        "# Lift\nLift = 0.5 * rho * V^2 * S * CL\n\n# Drag\nDrag = 0.5 * rho * V^2 * S * CD\n",
        encoding="utf-8",
    )
    md2 = tmp_path / "thermal_math.md"
    md2.write_text(
        "# Conduction\nFourier law: q = -k * dT/dx\n", encoding="utf-8",
    )
    kb = EngineeringKnowledgeBase.from_directory(tmp_path)
    assert len(kb.chunks) >= 3
    assert len(kb.domains) >= 2


def test_knowledge_base_from_repo_ai_knowledge() -> None:
    """Load the actual repo knowledge directory if it exists."""
    repo_dir = Path(__file__).resolve().parent.parent / "docs" / "ai_knowledge"
    if not repo_dir.is_dir():
        return  # skip if not available
    kb = EngineeringKnowledgeBase.from_directory(repo_dir)
    assert len(kb.chunks) > 0
    results = kb.search("structural stiffness deflection")
    assert len(results) > 0


# ── EngineeringQueryEngine ──────────────────────────────────────────────


def test_query_engine_basic_query() -> None:
    kb = EngineeringKnowledgeBase.from_texts(
        [
            "Bernoulli equation relates pressure and velocity in fluid flow.",
            "Euler-Bernoulli beam theory predicts bending deflection.",
            "Newton second law F = m * a.",
        ],
        domain="physics",
    )
    engine = EngineeringQueryEngine(knowledge_base=kb)
    result = engine.query("fluid flow pressure velocity")
    assert isinstance(result, QueryResult)
    assert result.confidence > 0.0
    assert len(result.passages) > 0
    assert "Bernoulli" in result.answer


def test_query_engine_no_results() -> None:
    kb = EngineeringKnowledgeBase.from_texts(["alpha beta gamma"])
    engine = EngineeringQueryEngine(knowledge_base=kb)
    result = engine.query("zzzzzzzzz")
    assert result.confidence == 0.0
    assert "No relevant" in result.answer


def test_query_engine_with_memory_store() -> None:
    kb = EngineeringKnowledgeBase.from_texts(
        ["Drag polar: CD = CD0 + CL^2 / (pi * e * AR)"],
        domain="aero",
    )
    mem = MemoryStore()
    mem.add("Previous analysis showed drag divergence at Mach 0.85", tags=["aero"])
    engine = EngineeringQueryEngine(knowledge_base=kb, memory_store=mem)
    result = engine.query("drag coefficient")
    assert result.confidence > 0.0
    # Memory events should be logged
    events = [r for r in mem.records if "ai_query" in r.tags]
    assert len(events) >= 1


def test_query_engine_domain_filter() -> None:
    kb = EngineeringKnowledgeBase()
    kb.chunks = [
        KnowledgeChunk(text="Lift force", source="a.md", heading="h", domain="aero"),
        KnowledgeChunk(text="Ohm law", source="b.md", heading="h", domain="circuits"),
    ]
    kb._build_index()
    engine = EngineeringQueryEngine(knowledge_base=kb)
    result = engine.query("force law", domain_filter="aero")
    assert all(
        "aero" in p.chunk.domain or p.chunk.domain == "memory"
        for p in result.passages
    )


def test_query_engine_list_domains() -> None:
    kb = EngineeringKnowledgeBase.from_texts(["x"], domain="thermal")
    engine = EngineeringQueryEngine(knowledge_base=kb)
    assert "thermal" in engine.list_domains()


def test_query_engine_to_dict() -> None:
    kb = EngineeringKnowledgeBase.from_texts(["x", "y"], domain="aero")
    engine = EngineeringQueryEngine(knowledge_base=kb)
    d = engine.to_dict()
    assert d["schema"] == "dark/engineering_ai/1.0"
    assert d["n_chunks"] == 2
    assert "aero" in d["domains"]
    assert d["has_memory"] is False


def test_query_engine_from_knowledge_dir(tmp_path: Path) -> None:
    md = tmp_path / "test_math.md"
    md.write_text(
        "# Basics\nForce equals mass times acceleration per Newton's second law.\n",
        encoding="utf-8",
    )
    engine = EngineeringQueryEngine.from_knowledge_dir(tmp_path)
    result = engine.query("force mass acceleration")
    assert result.confidence > 0.0


# ── Conversational context ──────────────────────────────────────────


def test_classify_intent_competition() -> None:
    intents = classify_intent("What are the DARPA LIFT competition rules?")
    assert len(intents) > 0
    intent_names = [i[0] for i in intents]
    assert "competition_rules" in intent_names


def test_classify_intent_cad() -> None:
    intents = classify_intent("Generate a CAD mesh for the drone")
    intent_names = [i[0] for i in intents]
    assert "cad_generate" in intent_names


def test_classify_intent_topology() -> None:
    intents = classify_intent("Optimize the topology for structural stiffness")
    intent_names = [i[0] for i in intents]
    assert "topology_optimize" in intent_names


def test_classify_intent_empty() -> None:
    intents = classify_intent("")
    assert intents == []


def test_classify_intent_no_match() -> None:
    intents = classify_intent("hello world zzzz")
    assert intents == []


def test_conversation_context_creation() -> None:
    ctx = ConversationContext()
    assert len(ctx.turns) == 0
    assert ctx.active_intents == {}
    assert ctx.design_parameters == {}


def test_conversation_context_add_turn() -> None:
    ctx = ConversationContext()
    turn = ctx.add_turn("user", "Build the competition drone with 4 motors")
    assert isinstance(turn, ConversationTurn)
    assert turn.role == "user"
    assert len(ctx.turns) == 1


def test_conversation_context_tracks_intents() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "What are the DARPA LIFT rules?")
    assert len(ctx.active_intents) > 0
    assert "competition_rules" in ctx.active_intents


def test_conversation_context_extracts_parameters() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "Build a drone with 6 motors and payload of 50 kg")
    assert ctx.design_parameters.get("arm_count") == 6
    assert ctx.design_parameters.get("payload_kg") == 50.0


def test_conversation_context_multi_turn() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "I want to build a competition drone")
    ctx.add_turn("assistant", "Sure, let me configure the DARPA LIFT quad.")
    ctx.add_turn("user", "Now generate the CAD mesh")
    assert len(ctx.turns) == 3
    assert "cad_generate" in ctx.active_intents


def test_conversation_context_dominant_intent() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "Generate a high-fidelity CAD mesh model for the drone")
    intent, confidence = ctx.get_dominant_intent()
    assert intent == "cad_generate"
    assert confidence > 0.0


def test_conversation_context_summary() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "Competition drone design with 4 motors 2.5 kg")
    summary = ctx.get_context_summary()
    assert "Turns: 1" in summary


def test_conversation_context_to_dict() -> None:
    ctx = ConversationContext()
    ctx.add_turn("user", "Optimize topology for the DARPA drone")
    d = ctx.to_dict()
    assert d["schema"] == "dark/conversation_context/1.0"
    assert d["turn_count"] == 1
    assert isinstance(d["active_intents"], dict)

