"""Machine learning and deep learning models for engineering surrogate modeling.

Provides a lightweight feedforward neural network built from the standard
library (no external ML frameworks required).  The network is trained via
backpropagation with gradient descent to learn mappings from design
parameters to performance metrics, enabling fast surrogate predictions
without running full physics simulations.

Key components
--------------
* ``FeatureScaler`` — min-max normalisation for input/output features.
* ``DenseLayer`` — single fully connected layer with optional ReLU activation.
* ``FeedForwardNetwork`` — variable-depth feedforward neural network.
* ``SurrogateModel`` — engineering surrogate wrapping the network with
  feature scaling, training, prediction, and JSON serialisation.

The surrogate is designed to be trained on data produced by the existing
pipeline (``pipeline.py``, ``design_loop.py``) so that the AI is
specifically trained on engineering data generated by this repository.
"""

from __future__ import annotations

import json
import math
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

# ── Feature scaling ──────────────────────────────────────────────────────


@dataclass
class FeatureScaler:
    """Min-max scaler that maps each feature to [0, 1]."""

    mins: List[float] = field(default_factory=list)
    maxs: List[float] = field(default_factory=list)

    def fit(self, data: Sequence[Sequence[float]]) -> None:
        if not data:
            return
        width = len(data[0])
        self.mins = [float("inf")] * width
        self.maxs = [float("-inf")] * width
        for row in data:
            for j in range(width):
                if row[j] < self.mins[j]:
                    self.mins[j] = row[j]
                if row[j] > self.maxs[j]:
                    self.maxs[j] = row[j]

    def transform(self, row: Sequence[float]) -> List[float]:
        out: List[float] = []
        for j, val in enumerate(row):
            span = self.maxs[j] - self.mins[j]
            out.append((val - self.mins[j]) / span if span > 0 else 0.5)
        return out

    def inverse_transform(self, row: Sequence[float]) -> List[float]:
        out: List[float] = []
        for j, val in enumerate(row):
            span = self.maxs[j] - self.mins[j]
            out.append(val * span + self.mins[j])
        return out

    def to_dict(self) -> Dict[str, Any]:
        return {"mins": self.mins, "maxs": self.maxs}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> FeatureScaler:
        return cls(mins=list(data["mins"]), maxs=list(data["maxs"]))


# ── Dense layer ──────────────────────────────────────────────────────────


def _relu(x: float) -> float:
    return max(0.0, x)


def _relu_derivative(x: float) -> float:
    return 1.0 if x > 0.0 else 0.0


@dataclass
class DenseLayer:
    """Single fully connected layer with optional ReLU activation."""

    weights: List[List[float]]
    biases: List[float]
    use_relu: bool = True

    @classmethod
    def create(
        cls, n_in: int, n_out: int, *, use_relu: bool = True, seed: int = 42
    ) -> DenseLayer:
        rng = random.Random(seed)
        # He initialisation for ReLU layers
        scale = math.sqrt(2.0 / max(n_in, 1))
        weights = [
            [rng.gauss(0.0, scale) for _ in range(n_in)] for _ in range(n_out)
        ]
        biases = [0.0] * n_out
        return cls(weights=weights, biases=biases, use_relu=use_relu)

    @property
    def n_in(self) -> int:
        return len(self.weights[0]) if self.weights else 0

    @property
    def n_out(self) -> int:
        return len(self.weights)

    def forward(self, x: List[float]) -> Tuple[List[float], List[float]]:
        """Return (activated_output, pre_activation) for backprop."""
        pre: List[float] = []
        for j in range(self.n_out):
            total = self.biases[j]
            for i in range(self.n_in):
                total += self.weights[j][i] * x[i]
            pre.append(total)
        if self.use_relu:
            activated = [_relu(z) for z in pre]
        else:
            activated = list(pre)
        return activated, pre

    def to_dict(self) -> Dict[str, Any]:
        return {
            "weights": self.weights,
            "biases": self.biases,
            "use_relu": self.use_relu,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> DenseLayer:
        return cls(
            weights=data["weights"],
            biases=data["biases"],
            use_relu=data.get("use_relu", True),
        )


# ── Feedforward network ─────────────────────────────────────────────────


@dataclass
class FeedForwardNetwork:
    """Multi-layer feedforward neural network (deep learning).

    Supports arbitrary depth and width.  Training uses mini-batch
    stochastic gradient descent with backpropagation.
    """

    layers: List[DenseLayer] = field(default_factory=list)

    @classmethod
    def create(
        cls,
        layer_sizes: Sequence[int],
        *,
        seed: int = 42,
    ) -> FeedForwardNetwork:
        """Build a network from a list of layer sizes.

        Example: ``[4, 16, 8, 1]`` creates a 4→16→8→1 network
        with ReLU on hidden layers and linear output.
        """
        layers: List[DenseLayer] = []
        for idx in range(len(layer_sizes) - 1):
            is_last = idx == len(layer_sizes) - 2
            layers.append(
                DenseLayer.create(
                    layer_sizes[idx],
                    layer_sizes[idx + 1],
                    use_relu=not is_last,
                    seed=seed + idx,
                )
            )
        return cls(layers=layers)

    def forward(
        self, x: List[float]
    ) -> Tuple[List[float], List[List[float]], List[List[float]]]:
        """Full forward pass returning (output, activations, pre_activations)."""
        activations: List[List[float]] = [x]
        pre_activations: List[List[float]] = []
        current = x
        for layer in self.layers:
            activated, pre = layer.forward(current)
            activations.append(activated)
            pre_activations.append(pre)
            current = activated
        return current, activations, pre_activations

    def predict(self, x: List[float]) -> List[float]:
        output, _, _ = self.forward(x)
        return output

    def _backprop(
        self,
        x: List[float],
        y_true: List[float],
    ) -> Tuple[List[List[List[float]]], List[List[float]], float]:
        """Compute gradients via backpropagation (MSE loss)."""
        output, activations, pre_activations = self.forward(x)
        n_out = len(output)
        loss = sum((output[j] - y_true[j]) ** 2 for j in range(n_out)) / max(n_out, 1)

        # Output layer delta
        delta = [
            2.0 * (output[j] - y_true[j]) / max(n_out, 1) for j in range(n_out)
        ]
        if self.layers[-1].use_relu:
            delta = [
                delta[j] * _relu_derivative(pre_activations[-1][j])
                for j in range(n_out)
            ]

        weight_grads: List[List[List[float]]] = []
        bias_grads: List[List[float]] = []

        for layer_idx in range(len(self.layers) - 1, -1, -1):
            layer = self.layers[layer_idx]
            prev_act = activations[layer_idx]
            w_grad = [
                [delta[j] * prev_act[i] for i in range(layer.n_in)]
                for j in range(layer.n_out)
            ]
            b_grad = list(delta)
            weight_grads.insert(0, w_grad)
            bias_grads.insert(0, b_grad)

            if layer_idx > 0:
                new_delta = [0.0] * layer.n_in
                for i in range(layer.n_in):
                    for j in range(layer.n_out):
                        new_delta[i] += layer.weights[j][i] * delta[j]
                prev_pre = pre_activations[layer_idx - 1]
                if self.layers[layer_idx - 1].use_relu:
                    new_delta = [
                        new_delta[i] * _relu_derivative(prev_pre[i])
                        for i in range(len(new_delta))
                    ]
                delta = new_delta

        return weight_grads, bias_grads, loss

    def train_step(
        self,
        x_batch: Sequence[Sequence[float]],
        y_batch: Sequence[Sequence[float]],
        learning_rate: float = 0.01,
    ) -> float:
        """One gradient descent step on a mini-batch.  Returns mean loss."""
        n = len(x_batch)
        if n == 0:
            return 0.0

        total_loss = 0.0
        accum_w: Optional[List[List[List[float]]]] = None
        accum_b: Optional[List[List[float]]] = None

        for x, y in zip(x_batch, y_batch, strict=False):
            wg, bg, loss = self._backprop(list(x), list(y))
            total_loss += loss
            if accum_w is None:
                accum_w = wg
                accum_b = bg
            else:
                for li in range(len(wg)):
                    for j in range(len(wg[li])):
                        for i in range(len(wg[li][j])):
                            accum_w[li][j][i] += wg[li][j][i]
                        assert accum_b is not None
                        accum_b[li][j] += bg[li][j]

        assert accum_w is not None and accum_b is not None
        for li, layer in enumerate(self.layers):
            for j in range(layer.n_out):
                for i in range(layer.n_in):
                    layer.weights[j][i] -= learning_rate * accum_w[li][j][i] / n
                layer.biases[j] -= learning_rate * accum_b[li][j] / n

        return total_loss / n

    def to_dict(self) -> Dict[str, Any]:
        return {"layers": [layer.to_dict() for layer in self.layers]}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> FeedForwardNetwork:
        return cls(layers=[DenseLayer.from_dict(ld) for ld in data["layers"]])


# ── Surrogate model ─────────────────────────────────────────────────────


@dataclass
class TrainingHistory:
    """Records loss over training epochs."""

    epoch_losses: List[float] = field(default_factory=list)

    @property
    def final_loss(self) -> float:
        return self.epoch_losses[-1] if self.epoch_losses else float("inf")


@dataclass
class SurrogateModel:
    """Engineering surrogate model wrapping a neural network.

    Designed to learn mappings from design parameters to performance
    metrics using data generated by the simulation pipeline, so that
    the model is specifically trained on engineering data.

    Parameters
    ----------
    feature_names : names of input features (design parameters).
    target_names : names of output targets (performance metrics).
    hidden_sizes : widths of hidden layers (default ``[16, 8]``).
    seed : random seed for reproducibility.
    """

    feature_names: List[str]
    target_names: List[str]
    network: Optional[FeedForwardNetwork] = None
    input_scaler: FeatureScaler = field(default_factory=FeatureScaler)
    output_scaler: FeatureScaler = field(default_factory=FeatureScaler)
    history: TrainingHistory = field(default_factory=TrainingHistory)
    _hidden_sizes: List[int] = field(default_factory=lambda: [16, 8])
    _seed: int = 42
    _trained: bool = False

    def is_trained(self) -> bool:
        return self._trained

    def train(
        self,
        x_data: Sequence[Sequence[float]],
        y_data: Sequence[Sequence[float]],
        *,
        epochs: int = 200,
        learning_rate: float = 0.01,
        batch_size: int = 16,
        seed: Optional[int] = None,
    ) -> TrainingHistory:
        """Train the surrogate on engineering data.

        Parameters
        ----------
        x_data : rows of input feature vectors.
        y_data : rows of target metric vectors.
        epochs : number of training epochs.
        learning_rate : SGD learning rate.
        batch_size : mini-batch size.
        seed : random seed for shuffling.

        Returns
        -------
        TrainingHistory with per-epoch loss.
        """
        if len(x_data) == 0:
            raise ValueError("Training data must not be empty.")

        n_in = len(x_data[0])
        n_out = len(y_data[0])

        self.input_scaler.fit(x_data)
        self.output_scaler.fit(y_data)

        x_scaled = [self.input_scaler.transform(row) for row in x_data]
        y_scaled = [self.output_scaler.transform(row) for row in y_data]

        layer_sizes = [n_in] + self._hidden_sizes + [n_out]
        self.network = FeedForwardNetwork.create(layer_sizes, seed=seed or self._seed)

        rng = random.Random(seed or self._seed)
        self.history = TrainingHistory()

        for _epoch in range(epochs):
            indices = list(range(len(x_scaled)))
            rng.shuffle(indices)
            epoch_loss = 0.0
            n_batches = 0
            for start in range(0, len(indices), batch_size):
                batch_idx = indices[start : start + batch_size]
                xb = [x_scaled[i] for i in batch_idx]
                yb = [y_scaled[i] for i in batch_idx]
                epoch_loss += self.network.train_step(xb, yb, learning_rate)
                n_batches += 1
            self.history.epoch_losses.append(epoch_loss / max(n_batches, 1))

        self._trained = True
        return self.history

    def predict(self, features: Sequence[float]) -> Dict[str, float]:
        """Predict performance metrics from design parameters.

        Returns a dict mapping target names to predicted values.
        """
        if self.network is None or not self._trained:
            raise RuntimeError("Model has not been trained yet.")
        scaled_input = self.input_scaler.transform(features)
        scaled_output = self.network.predict(scaled_input)
        raw_output = self.output_scaler.inverse_transform(scaled_output)
        return {name: raw_output[i] for i, name in enumerate(self.target_names)}

    def predict_batch(
        self, features_batch: Sequence[Sequence[float]]
    ) -> List[Dict[str, float]]:
        """Predict for multiple input rows."""
        return [self.predict(row) for row in features_batch]

    def save(self, path: Path) -> None:
        """Save model to JSON file."""
        payload: Dict[str, Any] = {
            "schema": "dark/surrogate_model/1.0",
            "feature_names": self.feature_names,
            "target_names": self.target_names,
            "hidden_sizes": self._hidden_sizes,
            "seed": self._seed,
            "trained": self._trained,
            "input_scaler": self.input_scaler.to_dict(),
            "output_scaler": self.output_scaler.to_dict(),
            "history": {"epoch_losses": self.history.epoch_losses},
        }
        if self.network is not None:
            payload["network"] = self.network.to_dict()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> SurrogateModel:
        """Load a saved surrogate model from JSON."""
        data = json.loads(path.read_text(encoding="utf-8"))
        model = cls(
            feature_names=data["feature_names"],
            target_names=data["target_names"],
            _hidden_sizes=data.get("hidden_sizes", [16, 8]),
            _seed=data.get("seed", 42),
            _trained=data.get("trained", False),
            input_scaler=FeatureScaler.from_dict(data["input_scaler"]),
            output_scaler=FeatureScaler.from_dict(data["output_scaler"]),
            history=TrainingHistory(
                epoch_losses=data.get("history", {}).get("epoch_losses", [])
            ),
        )
        if "network" in data:
            model.network = FeedForwardNetwork.from_dict(data["network"])
        return model

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the model to a dictionary."""
        result: Dict[str, Any] = {
            "schema": "dark/surrogate_model/1.0",
            "feature_names": self.feature_names,
            "target_names": self.target_names,
            "trained": self._trained,
            "final_loss": self.history.final_loss,
        }
        return result


# ── Convenience builder ──────────────────────────────────────────────────


def build_design_surrogate(
    hidden_sizes: Optional[List[int]] = None,
    seed: int = 42,
) -> SurrogateModel:
    """Create a surrogate for the standard design-loop feature set.

    Features correspond to VehicleParams fields; targets correspond
    to the design-loop score and key flight-test metrics.
    """
    feature_names = [
        "mass_kg",
        "wing_area_m2",
        "cd0",
        "max_thrust_n",
        "max_tilt_rad",
        "max_speed_m_s",
    ]
    target_names = [
        "design_score",
        "max_altitude_m",
        "max_speed_achieved_m_s",
        "sustained_turn_rate_deg_s",
        "min_battery_pct",
    ]
    return SurrogateModel(
        feature_names=feature_names,
        target_names=target_names,
        _hidden_sizes=hidden_sizes or [16, 8],
        _seed=seed,
    )
