#!/usr/bin/env python3
"""
Verify that a CMake compile_commands.json respects v2 gating expectations.

Use cases:
- OFF mode: fail if any entry references v2 sources/dirs (require-absent).
- ON mode: fail if expected v2 sources/dirs are missing (require-present).

The check is substring-based on normalized absolute file paths to avoid
environment-specific noise.
"""

import argparse
import json
import os
import sys
from typing import List, Sequence


def normalize(path: str) -> str:
    return os.path.abspath(path).replace("\\", "/")


def load_compile_db(path: str) -> List[str]:
    with open(path, "r", encoding="utf-8") as f:
        entries = json.load(f)
    return [normalize(entry["file"]) for entry in entries]


def find_matches(paths: Sequence[str], substrings: Sequence[str]) -> List[str]:
    matched = []
    for p in paths:
        for sub in substrings:
            if sub in p:
                matched.append(p)
                break
    return sorted(set(matched))


def ensure_present(paths: Sequence[str], substrings: Sequence[str]) -> List[str]:
    missing = []
    for sub in substrings:
        if not any(sub in p for p in paths):
            missing.append(sub)
    return missing


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify compile_commands.json isolation for v2 gating."
    )
    parser.add_argument(
        "--compile-db",
        required=True,
        help="Path to compile_commands.json generated by CMake.",
    )
    parser.add_argument(
        "--require-absent",
        action="append",
        default=[],
        help="Substring that must not appear in any compile command path (repeatable).",
    )
    parser.add_argument(
        "--require-present",
        action="append",
        default=[],
        help="Substring that must appear in at least one compile command path (repeatable).",
    )
    args = parser.parse_args()

    compile_db_path = os.path.abspath(args.compile_db)
    if not os.path.isfile(compile_db_path):
        if args.require_present:
            print(
                "[verify-compile-db] missing compile_commands.json "
                "(required for presence checks): "
                f"{compile_db_path}",
                file=sys.stderr,
            )
            return 1
        # No compile DB and only absence expectations: treat as empty and pass.
        print(
            "[verify-compile-db] compile_commands.json not found; "
            "treating as empty for absence checks: "
            f"{compile_db_path}"
        )
        paths = []
    else:
        paths = load_compile_db(compile_db_path)

    violations = []

    if args.require_absent:
        matches = find_matches(paths, args.require_absent)
        if matches:
            violations.append(
                f"Found disallowed entries ({len(matches)}):\n" + "\n".join(matches)
            )

    if args.require_present:
        missing = ensure_present(paths, args.require_present)
        if missing:
            violations.append(
                f"Missing required substrings ({len(missing)}): " + ", ".join(missing)
            )

    mode = []
    if args.require_absent:
        mode.append(f"absent={args.require_absent}")
    if args.require_present:
        mode.append(f"present={args.require_present}")
    mode_desc = "; ".join(mode) if mode else "no expectations"

    if violations:
        print(f"[verify-compile-db] FAILED ({mode_desc})", file=sys.stderr)
        for v in violations:
            print(v, file=sys.stderr)
        return 1

    print(f"[verify-compile-db] PASSED ({mode_desc}); checked {len(paths)} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
