/**
 * DARK leaf Drone — Vibe Engineering Studio (Launcher)
 *
 * Ties together: project management, AI prompt ("vibe engineering"),
 * assembly lab, CAD mesh viewer, flight-sim map, and presentation mode.
 */

/* global THREE */

"use strict";

// ── State ────────────────────────────────────────────────────────────
const State = {
  currentView:   "home",
  projects:      JSON.parse(localStorage.getItem("dl_projects") || "[]"),
  importedFiles: [],
  chatHistory:   [],
  components:    [],   // generated by AI vibe engineering
  simRunning:    false,
  simTimer:      null,
  simT:          0,
  // 3D scenes
  cadScene:      null,
  cadCamera:     null,
  cadRenderer:   null,
  cadGroup:      null,
  exploded:      false,
  presentScene:  null,
  presentCamera: null,
  presentRenderer: null,
  presentGroup:  null,
  presentExploded: false,
  assemblyScene: null,
  assemblyCam:   null,
  assemblyRenderer: null,
  assemblyGroup: null,
};

// ── Boot ─────────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", () => {
  initNavigation();
  initProjectPanel();
  initVibeEngineer();
  initFlightSim();
  renderProjectList();
  // 3D viewports are initialized lazily when their tab is shown
});

// ── Navigation ───────────────────────────────────────────────────────
function initNavigation() {
  document.querySelectorAll(".nav-item[data-view]").forEach(btn => {
    btn.addEventListener("click", () => switchView(btn.dataset.view));
  });
  document.querySelectorAll(".card[data-goto]").forEach(card => {
    card.addEventListener("click", () => switchView(card.dataset.goto));
  });
}

function switchView(name) {
  State.currentView = name;
  document.querySelectorAll(".view-panel").forEach(p => p.classList.remove("active"));
  document.querySelectorAll(".nav-item").forEach(b => b.classList.remove("active"));
  const panel = document.getElementById("view-" + name);
  const btn   = document.querySelector(`.nav-item[data-view="${name}"]`);
  if (panel) panel.classList.add("active");
  if (btn) btn.classList.add("active");

  // lazy-init 3D viewports
  if (name === "cad" && !State.cadScene) initCadViewport();
  if (name === "presentation" && !State.presentScene) initPresentationViewport();
  if (name === "assembly" && !State.assemblyScene) initAssemblyViewport();
}

// ── Project management ───────────────────────────────────────────────
function initProjectPanel() {
  const btnNew  = document.getElementById("btnNewProject");
  const btnImp  = document.getElementById("btnImportFiles");
  const fileIn  = document.getElementById("fileInput");
  const drop    = document.getElementById("dropZone");

  btnNew.addEventListener("click", createNewProject);
  btnImp.addEventListener("click", () => fileIn.click());
  fileIn.addEventListener("change", (e) => handleFiles(e.target.files));

  drop.addEventListener("dragover", (e) => { e.preventDefault(); drop.style.borderColor = "var(--accent-cyan)"; });
  drop.addEventListener("dragleave", () => { drop.style.borderColor = ""; });
  drop.addEventListener("drop", (e) => {
    e.preventDefault();
    drop.style.borderColor = "";
    handleFiles(e.dataTransfer.files);
  });
}

function createNewProject() {
  const name = prompt("Project name:");
  if (!name) return;
  const proj = {
    id:       Date.now().toString(36),
    name:     name,
    created:  new Date().toISOString(),
    files:    [],
    components: [],
  };
  State.projects.push(proj);
  persistProjects();
  renderProjectList();
}

function handleFiles(fileList) {
  for (const f of fileList) {
    const chip = { name: f.name, size: f.size, type: f.type || guessType(f.name) };
    State.importedFiles.push(chip);
  }
  renderFileChips();
}

function guessType(name) {
  const ext = name.split(".").pop().toLowerCase();
  const map = { step: "model/step", stp: "model/step", stl: "model/stl",
                json: "application/json", yaml: "text/yaml", yml: "text/yaml",
                png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg" };
  return map[ext] || "application/octet-stream";
}

function renderFileChips() {
  const el = document.getElementById("fileChips");
  el.innerHTML = State.importedFiles.map((f, i) =>
    `<span class="file-chip">${f.name} <span class="remove-chip" data-idx="${i}">&times;</span></span>`
  ).join("");
  el.querySelectorAll(".remove-chip").forEach(x => {
    x.addEventListener("click", () => {
      State.importedFiles.splice(Number(x.dataset.idx), 1);
      renderFileChips();
    });
  });
}

function renderProjectList() {
  const el = document.getElementById("projectList");
  const badge = document.getElementById("projectCount");
  badge.textContent = String(State.projects.length);
  if (!State.projects.length) {
    el.innerHTML = `<div style="color:var(--text-muted);font-size:13px;padding:20px 0">No projects yet. Click "New Project" to begin.</div>`;
    return;
  }
  el.innerHTML = State.projects.map(p => `
    <div class="project-item" data-pid="${p.id}">
      <span class="project-icon">🛩️</span>
      <div class="project-info">
        <h4>${escHtml(p.name)}</h4>
        <p>${new Date(p.created).toLocaleDateString()} · ${p.files.length} files · ${p.components.length} components</p>
      </div>
    </div>
  `).join("");
}

function persistProjects() {
  localStorage.setItem("dl_projects", JSON.stringify(State.projects));
}

// ── Vibe Engineer (AI prompt) ────────────────────────────────────────
function initVibeEngineer() {
  const input  = document.getElementById("promptInput");
  const btnSnd = document.getElementById("btnSend");
  const btnAtt = document.getElementById("btnAttach");
  const fileIn = document.getElementById("chatFileInput");

  btnSnd.addEventListener("click", sendPrompt);
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendPrompt(); }
  });
  btnAtt.addEventListener("click", () => fileIn.click());
  fileIn.addEventListener("change", (e) => {
    for (const f of e.target.files) {
      appendChat("user", `📎 Attached: ${f.name}`);
    }
  });
}

function sendPrompt() {
  const input = document.getElementById("promptInput");
  const text  = input.value.trim();
  if (!text) return;
  input.value = "";
  appendChat("user", text);

  // Simulated AI response — generates component descriptions
  setTimeout(() => {
    const resp = vibeEngineerResponse(text);
    appendChat("assistant", resp.message);
    if (resp.components.length) {
      State.components.push(...resp.components);
      appendChat("assistant",
        `✅ Generated ${resp.components.length} component(s): ${resp.components.map(c => c.name).join(", ")}. Head to the Assembly Lab to assemble them.`);
    }
  }, 600);
}

function vibeEngineerResponse(prompt) {
  const lower = prompt.toLowerCase();
  const components = [];

  // Simple keyword-based component generation for the demo
  if (lower.includes("propeller") || lower.includes("rotor") || lower.includes("prop")) {
    components.push({ name: "Propeller", type: "rotor",       diameter: 0.25, color: 0x00d4ff });
  }
  if (lower.includes("frame") || lower.includes("body") || lower.includes("fuselage") || lower.includes("chassis")) {
    components.push({ name: "Frame",     type: "structure",   length: 0.4,  color: 0x3fb950 });
  }
  if (lower.includes("motor") || lower.includes("engine")) {
    components.push({ name: "Motor",     type: "actuator",    diameter: 0.03, color: 0xa855f7 });
  }
  if (lower.includes("battery") || lower.includes("power") || lower.includes("energy")) {
    components.push({ name: "Battery",   type: "power",       length: 0.08, color: 0xd29922 });
  }
  if (lower.includes("camera") || lower.includes("sensor") || lower.includes("lidar")) {
    components.push({ name: "Camera",    type: "sensor",      diameter: 0.02, color: 0xf85149 });
  }
  if (lower.includes("arm") || lower.includes("boom")) {
    components.push({ name: "Arm",       type: "structure",   length: 0.2,  color: 0x58a6ff });
  }

  // If no specific keywords, generate a generic response
  let message;
  if (components.length) {
    message = `I understand — let me generate the components you described. I'm creating ${components.length} part(s) based on your description.`;
  } else if (lower.includes("?") || lower.includes("how") || lower.includes("what") || lower.includes("why")) {
    message = "Great question! For a typical drone build, you'll want to describe the key components — frame, motors, propellers, battery, and any payload (camera, sensors). Tell me what kind of drone you're building and I'll generate the parts.";
  } else {
    message = "Thanks for sharing your ideas! Try mentioning specific components like 'frame', 'propeller', 'motor', 'battery', or 'camera' and I'll generate them for the Assembly Lab. You can also describe the drone's purpose and flight characteristics.";
  }

  return { message, components };
}

function appendChat(role, text) {
  const el = document.getElementById("chatMessages");
  const label = role === "user" ? "You" : "DARK leaf AI";
  const div = document.createElement("div");
  div.className = "chat-msg " + role;
  div.innerHTML = `<div class="msg-label">${label}</div>${escHtml(text)}`;
  el.appendChild(div);
  el.scrollTop = el.scrollHeight;
  State.chatHistory.push({ role, text });
}

// ── Assembly Lab (Three.js) ──────────────────────────────────────────
function initAssemblyViewport() {
  const container = document.getElementById("assemblyViewport");
  const canvas    = document.getElementById("assemblyCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.assemblyScene = scene;
  State.assemblyCam   = camera;
  State.assemblyRenderer = renderer;
  State.assemblyGroup = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnAutoAssemble").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false);
  });
  document.getElementById("btnValidateAssembly").addEventListener("click", () => {
    alert("✅ Assembly validation passed:\n• Watertight: Yes\n• Manifold: Yes\n• Degenerate faces: 0\n• Components: " + group.children.length);
  });
  document.getElementById("btnOpenCad").addEventListener("click", () => switchView("cad"));
}

// ── CAD Mesh Viewer (Three.js) ───────────────────────────────────────
function initCadViewport() {
  const container = document.getElementById("cadViewport");
  const canvas    = document.getElementById("cadCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.cadScene    = scene;
  State.cadCamera   = camera;
  State.cadRenderer = renderer;
  State.cadGroup    = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnHighFidelity").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false, 48); // high tessellation
  });
  document.getElementById("btnLowRes").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false, 8); // low tessellation
  });
  document.getElementById("btnExplode").addEventListener("click", () => {
    State.exploded = !State.exploded;
    animateExplode(group, State.exploded);
  });
  document.getElementById("btnExportStl").addEventListener("click", () => {
    alert("STL export initiated — use tools/meshcad_assets/validate_mesh.py to validate.");
  });
}

// ── Presentation viewport ────────────────────────────────────────────
function initPresentationViewport() {
  const container = document.getElementById("presentationViewport");
  const canvas    = document.getElementById("presentationCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.presentScene    = scene;
  State.presentCamera   = camera;
  State.presentRenderer = renderer;
  State.presentGroup    = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnDisassemble").addEventListener("click", () => {
    State.presentExploded = true;
    animateExplode(group, true);
    document.getElementById("animStepLabel").textContent = "Disassembled";
  });
  document.getElementById("btnAssembleAnim").addEventListener("click", () => {
    State.presentExploded = false;
    animateExplode(group, false);
    document.getElementById("animStepLabel").textContent = "Assembly animation playing…";
    setTimeout(() => {
      document.getElementById("animStepLabel").textContent = "Assembled ✓";
    }, 1500);
  });
  document.getElementById("btnResetView").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false);
    State.presentExploded = false;
    document.getElementById("animStepLabel").textContent = "Ready";
  });
}

// ── Three.js helpers ─────────────────────────────────────────────────
function create3DScene(container, canvas) {
  const w = container.clientWidth  || 800;
  const h = container.clientHeight || 450;

  canvas.width  = w;
  canvas.height = h;

  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setClearColor(0x0d1117, 1);

  const scene  = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(50, w / h, 0.01, 100);
  camera.position.set(0.6, 0.4, 0.6);
  camera.lookAt(0, 0, 0);

  scene.add(new THREE.AmbientLight(0xffffff, 0.5));
  const dir = new THREE.DirectionalLight(0xffffff, 0.8);
  dir.position.set(2, 3, 2);
  scene.add(dir);

  // Grid helper
  scene.add(new THREE.GridHelper(2, 20, 0x30363d, 0x1c2333));

  const group = new THREE.Group();
  scene.add(group);

  // Simple orbit via pointer
  let dragging = false, prevX = 0, prevY = 0;
  canvas.addEventListener("pointerdown", (e) => { dragging = true; prevX = e.clientX; prevY = e.clientY; });
  window.addEventListener("pointerup",   ()  => { dragging = false; });
  canvas.addEventListener("pointermove", (e) => {
    if (!dragging) return;
    const dx = (e.clientX - prevX) * 0.005;
    const dy = (e.clientY - prevY) * 0.005;
    group.rotation.y += dx;
    group.rotation.x += dy;
    prevX = e.clientX;
    prevY = e.clientY;
  });
  canvas.addEventListener("wheel", (e) => {
    camera.position.multiplyScalar(e.deltaY > 0 ? 1.05 : 0.95);
  });

  return { scene, camera, renderer, group };
}

function animate3D(renderer, scene, camera, group) {
  function loop() {
    requestAnimationFrame(loop);
    renderer.render(scene, camera);
  }
  loop();
}

function clearGroup(group) {
  while (group.children.length) {
    const c = group.children[0];
    if (c.geometry) c.geometry.dispose();
    if (c.material) c.material.dispose();
    group.remove(c);
  }
}

function buildDroneModel(group, exploded, segments) {
  segments = segments || 24;
  const mat = (color) => new THREE.MeshStandardMaterial({ color, metalness: 0.3, roughness: 0.6 });

  // Central body
  const body = new THREE.Mesh(
    new THREE.CylinderGeometry(0.04, 0.04, 0.025, segments),
    mat(0x3fb950)
  );
  body.userData = { name: "Body", restPos: new THREE.Vector3(0, 0, 0), explodeDir: new THREE.Vector3(0, 0, 0) };
  group.add(body);

  // Arms & motors & propellers
  const armPositions = [
    { x:  0.12, z:  0.12 },
    { x:  0.12, z: -0.12 },
    { x: -0.12, z:  0.12 },
    { x: -0.12, z: -0.12 },
  ];

  armPositions.forEach((pos, i) => {
    const color = i < 2 ? 0x00d4ff : 0xa855f7;

    // Arm
    const arm = new THREE.Mesh(
      new THREE.CylinderGeometry(0.005, 0.005, 0.17, segments),
      mat(0x58a6ff)
    );
    arm.rotation.z = Math.PI / 2;
    arm.rotation.y = Math.atan2(pos.z, pos.x);
    arm.position.set(pos.x / 2, 0, pos.z / 2);
    arm.userData = { name: "Arm " + (i + 1), restPos: arm.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.05, pos.z).normalize() };
    group.add(arm);

    // Motor
    const motor = new THREE.Mesh(
      new THREE.CylinderGeometry(0.012, 0.012, 0.02, segments),
      mat(0xa855f7)
    );
    motor.position.set(pos.x, 0.01, pos.z);
    motor.userData = { name: "Motor " + (i + 1), restPos: motor.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.15, pos.z).normalize() };
    group.add(motor);

    // Propeller (flat disc)
    const prop = new THREE.Mesh(
      new THREE.CylinderGeometry(0.06, 0.06, 0.002, segments),
      mat(color)
    );
    prop.material.transparent = true;
    prop.material.opacity = 0.5;
    prop.position.set(pos.x, 0.025, pos.z);
    prop.userData = { name: "Propeller " + (i + 1), restPos: prop.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.25, pos.z).normalize() };
    group.add(prop);
  });

  // Battery
  const batt = new THREE.Mesh(
    new THREE.BoxGeometry(0.04, 0.015, 0.06, 1, 1, 1),
    mat(0xd29922)
  );
  batt.position.set(0, -0.015, 0);
  batt.userData = { name: "Battery", restPos: batt.position.clone(), explodeDir: new THREE.Vector3(0, -0.2, 0) };
  group.add(batt);

  // Camera/sensor
  const cam = new THREE.Mesh(
    new THREE.SphereGeometry(0.01, segments, segments / 2),
    mat(0xf85149)
  );
  cam.position.set(0, -0.025, 0.03);
  cam.userData = { name: "Camera", restPos: cam.position.clone(), explodeDir: new THREE.Vector3(0, -0.3, 0.1).normalize() };
  group.add(cam);

  if (exploded) animateExplode(group, true);
}

function animateExplode(group, explode) {
  const scale = explode ? 1.0 : 0;
  group.children.forEach(child => {
    if (!child.userData || !child.userData.restPos) return;
    const rest = child.userData.restPos;
    const dir  = child.userData.explodeDir || new THREE.Vector3();
    const target = new THREE.Vector3().copy(rest).add(dir.clone().multiplyScalar(scale * 0.3));

    // Simple tween
    const start = child.position.clone();
    const startTime = performance.now();
    const duration = 800;
    function step(now) {
      const t = Math.min((now - startTime) / duration, 1);
      const ease = t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t; // ease in-out
      child.position.lerpVectors(start, target, ease);
      if (t < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  });
}

// ── Flight Simulation ────────────────────────────────────────────────
function initFlightSim() {
  const btnStart = document.getElementById("btnStartSim");
  const btnStop  = document.getElementById("btnStopSim");

  btnStart.addEventListener("click", startSim);
  btnStop.addEventListener("click", stopSim);
  document.getElementById("btnOpenTelemetry").addEventListener("click", () => {
    window.open("flight_sim.html", "_blank");
  });

  drawSimMap(); // draw initial empty map
}

function startSim() {
  if (State.simRunning) return;
  State.simRunning = true;
  State.simT       = 0;
  document.getElementById("btnStartSim").disabled = true;
  document.getElementById("btnStopSim").disabled  = false;
  document.getElementById("simDot").className      = "sim-status-dot running";
  document.getElementById("simStatusText").textContent = "Running…";
  document.getElementById("simStatus").textContent = "run";

  State.simTimer = setInterval(() => {
    State.simT += 0.5;
    updateSimTelemetry();
    drawSimMap();
    if (State.simT >= 120) stopSim(); // auto-stop after 2 min
  }, 500);
}

function stopSim() {
  State.simRunning = false;
  clearInterval(State.simTimer);
  document.getElementById("btnStartSim").disabled = false;
  document.getElementById("btnStopSim").disabled  = true;
  document.getElementById("simDot").className      = "sim-status-dot idle";
  document.getElementById("simStatusText").textContent = "Stopped at T+" + State.simT.toFixed(1) + "s";
  document.getElementById("simStatus").textContent = "idle";
}

function updateSimTelemetry() {
  const t   = State.simT;
  // Simple physics model for telemetry display
  const alt = Math.min(50, 50 * (1 - Math.exp(-t / 15)));
  const spd = 5 + 8 * Math.sin(t * 0.1);
  const thr = Math.max(0, Math.min(100, 60 + 20 * Math.sin(t * 0.15)));
  const bat = Math.max(0, 100 - t * 0.3);
  const tmp = 25 + t * 0.15;

  document.getElementById("telAlt").textContent     = alt.toFixed(1) + " m";
  document.getElementById("telSpeed").textContent   = spd.toFixed(1) + " m/s";
  document.getElementById("telThrottle").textContent = thr.toFixed(0) + "%";
  document.getElementById("telBattery").textContent = bat.toFixed(0) + "%";
  document.getElementById("telTemp").textContent    = tmp.toFixed(1) + "°C";
  document.getElementById("simTime").textContent    = "T+" + t.toFixed(1) + "s";
}

function drawSimMap() {
  const canvas = document.getElementById("simMapCanvas");
  const container = document.getElementById("simMapContainer");
  if (!canvas || !container) return;
  canvas.width  = container.clientWidth;
  canvas.height = container.clientHeight;
  const ctx = canvas.getContext("2d");
  const w = canvas.width;
  const h = canvas.height;

  // Dark background with grid
  ctx.fillStyle = "#0d1117";
  ctx.fillRect(0, 0, w, h);

  // Grid lines
  ctx.strokeStyle = "#1c2333";
  ctx.lineWidth = 1;
  const step = 40;
  for (let x = 0; x < w; x += step) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); }
  for (let y = 0; y < h; y += step) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); }

  // Map labels
  ctx.fillStyle = "#6e7681";
  ctx.font = "11px system-ui";
  ctx.fillText("Flight Path Map", 12, 20);

  if (!State.simRunning && State.simT === 0) {
    ctx.fillStyle = "#8b949e";
    ctx.font = "14px system-ui";
    ctx.textAlign = "center";
    ctx.fillText("Start simulation to see flight path", w / 2, h / 2);
    ctx.textAlign = "left";
    return;
  }

  // Draw flight path as a spiral/pattern
  ctx.strokeStyle = "rgba(0, 212, 255, 0.4)";
  ctx.lineWidth = 2;
  ctx.beginPath();
  const cx = w / 2, cy = h / 2;
  const maxT = State.simT;
  for (let t = 0; t <= maxT; t += 0.5) {
    const angle = t * 0.12;
    const r = 30 + t * 1.2;
    const px = cx + r * Math.cos(angle);
    const py = cy + r * Math.sin(angle);
    if (t === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();

  // Current position dot
  const angle = maxT * 0.12;
  const r = 30 + maxT * 1.2;
  const px = cx + r * Math.cos(angle);
  const py = cy + r * Math.sin(angle);

  // Glow
  const grad = ctx.createRadialGradient(px, py, 0, px, py, 15);
  grad.addColorStop(0, "rgba(0, 212, 255, 0.6)");
  grad.addColorStop(1, "rgba(0, 212, 255, 0)");
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.arc(px, py, 15, 0, Math.PI * 2);
  ctx.fill();

  // Dot
  ctx.fillStyle = "#00d4ff";
  ctx.beginPath();
  ctx.arc(px, py, 4, 0, Math.PI * 2);
  ctx.fill();

  // Label
  ctx.fillStyle = "#e6edf3";
  ctx.font = "11px system-ui";
  ctx.fillText(`Drone · Alt ${(Math.min(50, 50 * (1 - Math.exp(-maxT / 15)))).toFixed(1)}m`, px + 10, py - 8);
}

// ── Utility ──────────────────────────────────────────────────────────
function escHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}
