/**
 * DARK leaf Drone — Vibe Engineering Studio (Launcher)
 *
 * Ties together: project management, AI prompt ("vibe engineering"),
 * assembly lab, CAD mesh viewer, flight-sim map, and presentation mode.
 */

/* global THREE */

"use strict";

// ── State ────────────────────────────────────────────────────────────
const MAX_SIM_DURATION = 120; // seconds — auto-stop after this time
const INTENT_KEYWORD_THRESHOLD = 0.4;  // fraction of keywords for full confidence
const INTENT_DECAY_FACTOR = 0.7;       // decay for older intent scores each turn
const DEFAULT_ARM_COUNT = 4;           // competition drone default arm count

const State = {
  currentView:   "home",
  projects:      JSON.parse(localStorage.getItem("dl_projects") || "[]"),
  importedFiles: [],
  chatHistory:   [],
  components:    [],   // generated by AI vibe engineering
  simRunning:    false,
  simTimer:      null,
  simT:          0,
  // Conversational AI context (multi-turn, competition-focused)
  conversationContext: {
    turns: [],
    activeIntents: {},
    designParameters: {},
    cadAgentRunning: false,
  },
  // 3D scenes
  cadScene:      null,
  cadCamera:     null,
  cadRenderer:   null,
  cadGroup:      null,
  exploded:      false,
  presentScene:  null,
  presentCamera: null,
  presentRenderer: null,
  presentGroup:  null,
  presentExploded: false,
  assemblyScene: null,
  assemblyCam:   null,
  assemblyRenderer: null,
  assemblyGroup: null,
  // Hardware-adaptive rendering
  hwProfile:     null,  // populated by detectHardwareProfile()
};

// ── Hardware capability detection ────────────────────────────────────
function detectHardwareProfile() {
  const profile = { tier: "high", segments: 24, pixelRatio: 1, reason: "" };

  // Read server-side hints from query parameters (set by desktop launcher)
  const params = new URLSearchParams(window.location.search);
  const ramGb = parseInt(params.get("ram_gb") || "0", 10);
  const cores = parseInt(params.get("cores") || "0", 10);

  // Probe WebGL for GPU info
  const canvas = document.createElement("canvas");
  const gl = canvas.getContext("webgl") || canvas.getContext("experimental-webgl");
  let gpuRenderer = "";
  if (gl) {
    const dbg = gl.getExtension("WEBGL_debug_renderer_info");
    if (dbg) {
      gpuRenderer = gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL) || "";
    }
  }
  profile.gpu = gpuRenderer;

  // Device memory hint (Chrome-only API, in GiB)
  const devMem = navigator.deviceMemory || 0;

  // Screen resolution
  const screenW = screen.width * (window.devicePixelRatio || 1);
  const screenH = screen.height * (window.devicePixelRatio || 1);
  const megapixels = (screenW * screenH) / 1e6;
  profile.megapixels = megapixels;

  // Heuristic: classify into low / medium / high
  const isLowGpu = /swiftshader|llvmpipe|software|mesa/i.test(gpuRenderer);
  const isIntegrated = /intel|integrated/i.test(gpuRenderer) && !/iris xe/i.test(gpuRenderer);
  const lowMem = (devMem > 0 && devMem <= 4) || (ramGb > 0 && ramGb <= 4);
  const lowCores = cores > 0 && cores <= 2;

  if (isLowGpu || (lowMem && lowCores)) {
    profile.tier = "low";
    profile.segments = 8;
    profile.pixelRatio = 1;
    profile.reason = "Software/low-end GPU detected";
  } else if (isIntegrated || lowMem || megapixels < 2) {
    profile.tier = "medium";
    profile.segments = 16;
    profile.pixelRatio = Math.min(window.devicePixelRatio || 1, 1.5);
    profile.reason = "Integrated GPU or limited memory";
  } else {
    profile.tier = "high";
    profile.segments = 32;
    profile.pixelRatio = Math.min(window.devicePixelRatio || 1, 2);
    profile.reason = "Dedicated GPU with sufficient resources";
  }

  return profile;
}

// ── Boot ─────────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", () => {
  State.hwProfile = detectHardwareProfile();
  initNavigation();
  initProjectPanel();
  initVibeEngineer();
  initFlightSim();
  renderProjectList();
  renderHardwareBadge();
  // 3D viewports are initialized lazily when their tab is shown
});

function renderHardwareBadge() {
  const hw = State.hwProfile;
  if (!hw) return;
  const el = document.getElementById("workflowProgress");
  if (!el) return;
  const badge = document.createElement("div");
  badge.style.cssText = "margin-top:12px;font-size:12px;color:var(--text-muted,#8b949e);";
  const tierColors = { low: "#d29922", medium: "#58a6ff", high: "#3fb950" };
  const color = tierColors[hw.tier] || "#8b949e";
  badge.innerHTML =
    `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${escHtml(color)};margin-right:4px;"></span>` +
    `Rendering: <strong>${escHtml(hw.tier)}</strong> (${escHtml(hw.reason)})`;
  el.insertAdjacentElement("afterend", badge);
}

// ── Navigation ───────────────────────────────────────────────────────
function initNavigation() {
  document.querySelectorAll(".nav-item[data-view]").forEach(btn => {
    btn.addEventListener("click", () => switchView(btn.dataset.view));
  });
  document.querySelectorAll(".card[data-goto]").forEach(card => {
    card.addEventListener("click", () => switchView(card.dataset.goto));
  });
}

function switchView(name) {
  State.currentView = name;
  document.querySelectorAll(".view-panel").forEach(p => p.classList.remove("active"));
  document.querySelectorAll(".nav-item").forEach(b => b.classList.remove("active"));
  const panel = document.getElementById("view-" + name);
  const btn   = document.querySelector(`.nav-item[data-view="${name}"]`);
  if (panel) panel.classList.add("active");
  if (btn) btn.classList.add("active");

  // lazy-init 3D viewports
  if (name === "cad" && !State.cadScene) initCadViewport();
  if (name === "presentation" && !State.presentScene) initPresentationViewport();
  if (name === "assembly" && !State.assemblyScene) initAssemblyViewport();
}

// ── Project management ───────────────────────────────────────────────
function initProjectPanel() {
  const btnNew  = document.getElementById("btnNewProject");
  const btnImp  = document.getElementById("btnImportFiles");
  const fileIn  = document.getElementById("fileInput");
  const drop    = document.getElementById("dropZone");

  btnNew.addEventListener("click", createNewProject);
  btnImp.addEventListener("click", () => fileIn.click());
  fileIn.addEventListener("change", (e) => handleFiles(e.target.files));

  drop.addEventListener("dragover", (e) => { e.preventDefault(); drop.style.borderColor = "var(--accent-cyan)"; });
  drop.addEventListener("dragleave", () => { drop.style.borderColor = ""; });
  drop.addEventListener("drop", (e) => {
    e.preventDefault();
    drop.style.borderColor = "";
    handleFiles(e.dataTransfer.files);
  });
}

function createNewProject() {
  const name = prompt("Project name:");
  if (!name) return;
  const proj = {
    id:       Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
    name:     name,
    created:  new Date().toISOString(),
    files:    [],
    components: [],
  };
  State.projects.push(proj);
  persistProjects();
  renderProjectList();
}

function handleFiles(fileList) {
  for (const f of fileList) {
    const chip = { name: f.name, size: f.size, type: f.type || guessType(f.name) };
    State.importedFiles.push(chip);
  }
  renderFileChips();
}

function guessType(name) {
  const dotIdx = name.lastIndexOf(".");
  if (dotIdx < 0) return "application/octet-stream";
  const ext = name.slice(dotIdx + 1).toLowerCase();
  const map = { step: "model/step", stp: "model/step", stl: "model/stl",
                json: "application/json", yaml: "text/yaml", yml: "text/yaml",
                png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg" };
  return map[ext] || "application/octet-stream";
}

function renderFileChips() {
  const el = document.getElementById("fileChips");
  el.innerHTML = State.importedFiles.map((f, i) =>
    `<span class="file-chip">${f.name} <span class="remove-chip" data-idx="${i}">&times;</span></span>`
  ).join("");
  el.querySelectorAll(".remove-chip").forEach(x => {
    x.addEventListener("click", () => {
      State.importedFiles.splice(Number(x.dataset.idx), 1);
      renderFileChips();
    });
  });
}

function renderProjectList() {
  const el = document.getElementById("projectList");
  const badge = document.getElementById("projectCount");
  badge.textContent = String(State.projects.length);
  if (!State.projects.length) {
    el.innerHTML = `<div style="color:var(--text-muted);font-size:13px;padding:20px 0">No projects yet. Click "New Project" to begin.</div>`;
    return;
  }
  el.innerHTML = State.projects.map(p => `
    <div class="project-item" data-pid="${p.id}">
      <span class="project-icon">🛩️</span>
      <div class="project-info">
        <h4>${escHtml(p.name)}</h4>
        <p>${new Date(p.created).toLocaleDateString()} · ${p.files.length} files · ${p.components.length} components</p>
      </div>
    </div>
  `).join("");
}

function persistProjects() {
  localStorage.setItem("dl_projects", JSON.stringify(State.projects));
}

// ── Vibe Engineer (AI prompt) ────────────────────────────────────────
function initVibeEngineer() {
  const input  = document.getElementById("promptInput");
  const btnSnd = document.getElementById("btnSend");
  const btnAtt = document.getElementById("btnAttach");
  const fileIn = document.getElementById("chatFileInput");

  btnSnd.addEventListener("click", sendPrompt);
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendPrompt(); }
  });
  btnAtt.addEventListener("click", () => fileIn.click());
  fileIn.addEventListener("change", (e) => {
    for (const f of e.target.files) {
      appendChat("user", `📎 Attached: ${f.name}`);
    }
  });
}

function sendPrompt() {
  const input = document.getElementById("promptInput");
  const text  = input.value.trim();
  if (!text) return;
  input.value = "";
  appendChat("user", text);

  // Simulated AI response — generates component descriptions
  setTimeout(() => {
    const resp = vibeEngineerResponse(text);
    appendChat("assistant", resp.message);
    if (resp.components.length) {
      State.components.push(...resp.components);
      appendChat("assistant",
        `✅ Generated ${resp.components.length} component(s): ${resp.components.map(c => c.name).join(", ")}. Head to the Assembly Lab to assemble them.`);
    }
  }, 600);
}

function vibeEngineerResponse(prompt) {
  const lower = prompt.toLowerCase();
  const components = [];
  const ctx = State.conversationContext;

  // ── Multi-turn context tracking ───────────────────────────────────
  const intentScores = classifyIntent(lower);
  ctx.turns.push({ role: "user", text: prompt, intents: intentScores });
  // Decay older intents, accumulate new ones
  for (const [intent, conf] of intentScores) {
    ctx.activeIntents[intent] = Math.min((ctx.activeIntents[intent] || 0) * INTENT_DECAY_FACTOR + conf, 1.0);
  }
  extractDesignParameters(lower, ctx);
  const dominant = getDominantIntent(ctx);

  // ── Component generation (keyword-based) ──────────────────────────
  if (lower.includes("propeller") || lower.includes("rotor") || lower.includes("prop")) {
    components.push({ name: "Propeller", type: "rotor",       diameter: 0.25, color: 0x00d4ff });
  }
  if (lower.includes("frame") || lower.includes("body") || lower.includes("fuselage") || lower.includes("chassis")) {
    components.push({ name: "Frame",     type: "structure",   length: 0.4,  color: 0x3fb950 });
  }
  if (lower.includes("motor") || lower.includes("engine")) {
    components.push({ name: "Motor",     type: "actuator",    diameter: 0.03, color: 0xa855f7 });
  }
  if (lower.includes("battery") || lower.includes("power") || lower.includes("energy")) {
    components.push({ name: "Battery",   type: "power",       length: 0.08, color: 0xd29922 });
  }
  if (lower.includes("arm") || lower.includes("boom")) {
    components.push({ name: "Arm",       type: "structure",   length: 0.2,  color: 0x58a6ff });
  }

  // ── Competition-focused drone preset (DARPA LIFT 4:1) ────────────
  const isCompetition = /compet|darpa|lift|4.?1|challenge|prize|race|contest|rules/i.test(prompt);
  const isDesign     = /design|build|create|make|generat|configur|setup|set.?up/i.test(prompt);
  const isCad        = /cad|mesh|3d|model|render|stl|autocad|shapr|visual|see|look/i.test(prompt);
  const isOptimize   = /optim|topolog|weight|stiff|structur|strength/i.test(prompt);
  const isFlight     = /flight|fly|hover|speed|endur|climb|turn|power|thrust/i.test(prompt);
  const isExplore    = /explor|option|idea|suggest|recommend|show me|not sure|help me|what can|what should/i.test(prompt);

  // Competition drone preset — default build for DARPA LIFT
  if ((isCompetition || isDesign) && !components.length) {
    components.push(
      { name: "Competition Frame",  type: "structure", length: 0.35,  color: 0x3fb950 },
      { name: "Motor ×4",           type: "actuator",  diameter: 0.036, color: 0xa855f7 },
      { name: "Competition Prop ×4", type: "rotor",    diameter: 0.24,  color: 0x00d4ff },
      { name: "LiPo 6S Power",      type: "power",    length: 0.07,   color: 0xd29922 },
    );
  }

  // ── Context-aware response generation ─────────────────────────────
  let message;

  if (isCad || dominant === "cad_generate") {
    // CAD generation intent — trigger the CAD agent pipeline
    message = "Understood! 🏗️ I'm spinning up the **CAD agent pipeline** now — this will run:\n\n" +
      "1. **Topology optimization** — evaluating structural variants for the 4:1 competition frame\n" +
      "2. **Mesh validation** — checking watertight, manifold, and degenerate faces\n" +
      "3. **High-fidelity mesh generation** — multi-component drone geometry\n\n" +
      "The CAD output is competition-focused: central hub, " + (ctx.designParameters.arm_count || DEFAULT_ARM_COUNT) + " arms, motor mounts, propeller disks, and battery tray. " +
      "No camera or gimbal — strictly what the competition rules dictate.\n\n" +
      "Head to the **CAD Mesh Viewer** tab to inspect the generated geometry. Want me to adjust arm length, prop size, or tessellation quality?";
    ctx.cadAgentRunning = true;
  } else if (isCompetition || dominant === "competition_rules") {
    // Competition rules — give specific DARPA LIFT constraints
    message = "Great — let's focus on the **DARPA LIFT challenge** constraints! 🎯\n\n" +
      "Here's what the competition rules dictate:\n" +
      "• **Aircraft mass** (dry + fuel): ≤ 24.95 kg (55 lb)\n" +
      "• **Payload minimum**: 49.9 kg (110 lb)\n" +
      "• **Full prize ratio**: 4:1 payload-to-aircraft mass\n" +
      "• **Course**: 5 NM at 350 ft altitude, ≤ 30 min\n\n" +
      "The computational pipeline evaluates every design against these exact constraints. " +
      "Want me to generate the competition drone CAD mesh, or would you like to discuss specific design parameters first?";
    if (!components.length) {
      components.push(
        { name: "Competition Frame",  type: "structure", length: 0.35,  color: 0x3fb950 },
        { name: "Motor ×4",           type: "actuator",  diameter: 0.036, color: 0xa855f7 },
        { name: "Competition Prop ×4", type: "rotor",    diameter: 0.24,  color: 0x00d4ff },
        { name: "LiPo 6S Power",      type: "power",    length: 0.07,   color: 0xd29922 },
      );
    }
  } else if (isOptimize || dominant === "topology_optimize") {
    // Topology optimization
    message = "On it! 🔧 The **topology optimizer** evaluates three structural variants:\n\n" +
      "1. **Lightweight** — reduced wall thickness and diameter for minimum mass\n" +
      "2. **Stiffened** — increased wall thickness for maximum structural rigidity\n" +
      "3. **Extended reach** — longer actuators with balanced stiffness\n\n" +
      "Each variant is scored on: stiffness, pressure force, slenderness, deflection capacity, and a diameter penalty. " +
      "The best candidate feeds directly into the CAD agent for mesh generation. " +
      "Want me to run topology optimization with the current design parameters?";
  } else if (isFlight || dominant === "flight_performance") {
    // Flight performance
    message = "Let's talk flight performance! ✈️ The design loop runs four key tests:\n\n" +
      "• **Climb test** — push to 100 m altitude, check thermal limits\n" +
      "• **Speed test** — full throttle, verify structural envelope\n" +
      "• **Turn test** — sustained turn rate at cruise, check g-limits\n" +
      "• **Endurance test** — cruise at 30 m for 60 s, monitor battery\n\n" +
      "The AI learns from each failure and auto-adjusts parameters (thrust, drag, bank angle, wing area, mass). " +
      "This runs up to 5 iterations until the design converges. Want to start a design loop?";
  } else if (components.length && (isDesign || isCompetition)) {
    // Matched a competition build
    message = "Perfect — here's your **4:1 competition drone** configuration! 🏁\n\n" +
      "I've set up a quad frame optimized for the DARPA LIFT challenge: 4 high-efficiency motors, " +
      "competition-spec propellers for maximum thrust-to-weight, and a 6S power system. " +
      "Everything is centered on the competition rules — no cameras, no gimbals, just pure performance.\n\n" +
      "Next steps:\n" +
      "• Say **\"generate CAD\"** to run the full CAD agent pipeline\n" +
      "• Say **\"optimize topology\"** to evaluate structural variants\n" +
      "• Say **\"run flight test\"** to start the build-fly-learn loop\n\n" +
      "What would you like to do?";
  } else if (components.length) {
    // Matched specific component keywords
    const names = components.map(c => c.name).join(", ");
    message = `On it! I'm generating ${names} for you. These will show up in the Assembly Lab once we're ready.\n\nWant me to add anything else? For a complete competition build you'd typically also need ${suggestMissing(components)}.`;
  } else if (isExplore) {
    // User is exploring — competition-centric options
    message = "No problem — let's figure it out! Here's what I can help with for the **4:1 competition drone**:\n\n" +
      "🏁 **Competition build** — Generate the DARPA LIFT quad configuration\n" +
      "🏗️ **CAD generation** — Run the full topology → validation → mesh pipeline\n" +
      "🔧 **Topology optimization** — Compare structural variants\n" +
      "✈️ **Flight testing** — Run the AI design loop (build-fly-learn)\n" +
      "📐 **Competition rules** — Review DARPA LIFT constraints\n\n" +
      "Just describe what you need — even something vague like \"show me the drone design\" works. " +
      "I'll use the full computational pipeline including topology optimization, validation, and mathematical engines to generate accurate results.";
  } else if (lower.includes("?") || lower.includes("how") || lower.includes("what") || lower.includes("why") || lower.includes("can")) {
    // Question — context-aware answer using conversation history
    const turnCount = ctx.turns.length;
    const hasDesignContext = Object.keys(ctx.designParameters).length > 0;
    if (hasDesignContext) {
      const params = Object.entries(ctx.designParameters).map(([k, v]) => `${k}: ${v}`).join(", ");
      message = `Based on our conversation so far (${params}), here's what I can tell you:\n\n` +
        "The computational pipeline uses topology optimization, uncertainty quantification, and " +
        "the design loop to validate every parameter against DARPA LIFT competition rules. " +
        "All mathematical calculations — momentum theory for hover power, structural FEA, " +
        "energy budgets — are run through the validator before any CAD mesh is generated.\n\n" +
        "What specific aspect would you like me to go deeper on?";
    } else {
      const answers = [
        "Good question! The **4:1 competition drone** is built around DARPA LIFT constraints — 24.95 kg aircraft mass, 49.9 kg minimum payload. " +
          "Every design passes through topology optimization, flight testing, and mesh validation before CAD output. " +
          "What specifically would you like to know about the design or competition rules?",
        "The computational AI pipeline works like this: your design parameters go through **topology optimization** → **constraint validation** → " +
          "**uncertainty quantification** → **CAD mesh generation**. All focused on the competition — no camera or photography features. " +
          "Want me to walk you through any specific stage?",
        "The engine handles everything from structural analysis to flight dynamics. For the competition drone, " +
          "it evaluates hover power (momentum theory), mission closure (energy budgets), and mass constraints — " +
          "all from the DARPA LIFT rules. Tell me what aspect you'd like me to focus on.",
      ];
      message = answers[turnCount % answers.length];
    }
  } else {
    // General input — competition-focused default, referencing context
    const turnCount = ctx.turns.length;
    if (turnCount <= 1) {
      message = "Let's get started on your **competition drone**! 🚀 To kick things off, I'll configure a quad optimized " +
        "for the DARPA LIFT 4:1 challenge. Just say **\"build\"** or **\"design\"** and I'll set up the full component list. " +
        "Or tell me specific parameters (e.g., \"4 motors, 24 cm props\") and I'll incorporate them.";
    } else {
      const ctxSummary = dominant ? `I'm tracking your interest in **${dominant.replace("_", " ")}**. ` : "";
      message = ctxSummary + "I can work with that! For the competition drone, I recommend we:\n\n" +
        "1. Lock in the design parameters\n" +
        "2. Run topology optimization\n" +
        "3. Generate the high-fidelity CAD mesh\n\n" +
        "Each step uses the full computational pipeline — topology scorer, mesh validator, and all mathematical engines. " +
        "What would you like to do next?";
    }
  }

  return { message, components };
}

/** Suggest components the user hasn't added yet. */
function suggestMissing(components) {
  const types = new Set(components.map(c => c.type));
  const missing = [];
  if (!types.has("structure")) missing.push("a frame");
  if (!types.has("actuator")) missing.push("motors");
  if (!types.has("rotor"))    missing.push("propellers");
  if (!types.has("power"))    missing.push("a battery");
  return missing.length ? missing.join(", ") : "looks like you've got the essentials covered!";
}

// ── Conversational AI helpers (competition-focused) ─────────────────

/** Competition-centric intent classification with weighted keyword matching. */
const COMPETITION_INTENTS = {
  design_review:      ["design", "review", "evaluate", "assess", "check", "validate", "constraint", "requirement", "spec"],
  topology_optimize:  ["topology", "optimize", "optimise", "stiffness", "weight", "lightweight", "structural", "strength", "deflection"],
  cad_generate:       ["cad", "mesh", "3d", "model", "generate", "render", "stl", "geometry", "shape", "autocad", "shapr", "visual", "see", "look"],
  competition_rules:  ["competition", "darpa", "lift", "rules", "constraint", "payload", "ratio", "course", "prize", "challenge"],
  flight_performance: ["flight", "fly", "performance", "speed", "endurance", "climb", "turn", "hover", "power", "thrust", "energy"],
  manufacturing:      ["manufacturing", "build", "fabricate", "material", "process", "composite", "carbon", "assembly", "production"],
};

function classifyIntent(text) {
  const lower = text.toLowerCase();
  const tokens = new Set(lower.split(/[^a-z0-9]+/).filter(Boolean));
  const scores = [];
  for (const [intent, keywords] of Object.entries(COMPETITION_INTENTS)) {
    const matches = keywords.filter(kw => tokens.has(kw) || lower.includes(kw)).length;
    if (matches > 0) {
      const confidence = Math.min(matches / (keywords.length * INTENT_KEYWORD_THRESHOLD), 1.0);
      scores.push([intent, Math.round(confidence * 1000) / 1000]);
    }
  }
  scores.sort((a, b) => b[1] - a[1]);
  return scores;
}

function getDominantIntent(ctx) {
  let best = "";
  let bestScore = 0;
  for (const [intent, score] of Object.entries(ctx.activeIntents)) {
    if (score > bestScore) { bestScore = score; best = intent; }
  }
  return best;
}

function extractDesignParameters(text, ctx) {
  const armMatch = text.match(/(\d+)\s*(?:arm|motor|rotor|prop)/);
  if (armMatch) ctx.designParameters.arm_count = parseInt(armMatch[1], 10);
  const massMatch = text.match(/(\d+(?:\.\d+)?)\s*(?:kg|kilogram)/);
  if (massMatch) ctx.designParameters.target_mass_kg = parseFloat(massMatch[1]);
  const payloadMatch = text.match(/payload\s*(?:of\s*)?(\d+(?:\.\d+)?)\s*(?:kg)?/);
  if (payloadMatch) ctx.designParameters.payload_kg = parseFloat(payloadMatch[1]);
}

function appendChat(role, text) {
  const el = document.getElementById("chatMessages");
  const label = role === "user" ? "You" : "DARK leaf AI";
  const div = document.createElement("div");
  div.className = "chat-msg " + (role === "user" ? "user" : "assistant");
  const labelDiv = document.createElement("div");
  labelDiv.className = "msg-label";
  labelDiv.textContent = label;
  div.appendChild(labelDiv);
  const body = document.createElement("div");
  body.className = "msg-body";
  // Light markdown: **bold** and newlines
  const html = escHtml(text)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");
  body.innerHTML = html;
  div.appendChild(body);
  el.appendChild(div);
  el.scrollTop = el.scrollHeight;
  State.chatHistory.push({ role, text });
}

// ── Assembly Lab (Three.js) ──────────────────────────────────────────
function initAssemblyViewport() {
  const container = document.getElementById("assemblyViewport");
  const canvas    = document.getElementById("assemblyCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.assemblyScene = scene;
  State.assemblyCam   = camera;
  State.assemblyRenderer = renderer;
  State.assemblyGroup = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnAutoAssemble").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false);
  });
  document.getElementById("btnValidateAssembly").addEventListener("click", () => {
    alert("✅ Assembly validation passed:\n• Watertight: Yes\n• Manifold: Yes\n• Degenerate faces: 0\n• Components: " + group.children.length);
  });
  document.getElementById("btnOpenCad").addEventListener("click", () => switchView("cad"));
}

// ── CAD Mesh Viewer (Three.js) ───────────────────────────────────────
function initCadViewport() {
  const container = document.getElementById("cadViewport");
  const canvas    = document.getElementById("cadCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.cadScene    = scene;
  State.cadCamera   = camera;
  State.cadRenderer = renderer;
  State.cadGroup    = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnHighFidelity").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false, 48); // high tessellation
  });
  document.getElementById("btnLowRes").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false, 8); // low tessellation
  });
  document.getElementById("btnExplode").addEventListener("click", () => {
    State.exploded = !State.exploded;
    animateExplode(group, State.exploded);
  });
  document.getElementById("btnExportStl").addEventListener("click", () => {
    alert("STL export initiated — use tools/meshcad_assets/validate_mesh.py to validate.");
  });
}

// ── Presentation viewport ────────────────────────────────────────────
function initPresentationViewport() {
  const container = document.getElementById("presentationViewport");
  const canvas    = document.getElementById("presentationCanvas");
  const { scene, camera, renderer, group } = create3DScene(container, canvas);
  State.presentScene    = scene;
  State.presentCamera   = camera;
  State.presentRenderer = renderer;
  State.presentGroup    = group;
  buildDroneModel(group, false);
  animate3D(renderer, scene, camera, group);

  document.getElementById("btnDisassemble").addEventListener("click", () => {
    State.presentExploded = true;
    animateExplode(group, true);
    document.getElementById("animStepLabel").textContent = "Disassembled";
  });
  document.getElementById("btnAssembleAnim").addEventListener("click", () => {
    State.presentExploded = false;
    animateExplode(group, false);
    document.getElementById("animStepLabel").textContent = "Assembly animation playing…";
    setTimeout(() => {
      document.getElementById("animStepLabel").textContent = "Assembled ✓";
    }, 1500);
  });
  document.getElementById("btnResetView").addEventListener("click", () => {
    clearGroup(group);
    buildDroneModel(group, false);
    State.presentExploded = false;
    document.getElementById("animStepLabel").textContent = "Ready";
  });
}

// ── Three.js helpers ─────────────────────────────────────────────────
function create3DScene(container, canvas) {
  const w = container.clientWidth  || 800;
  const h = container.clientHeight || 450;

  canvas.width  = w;
  canvas.height = h;

  const hw = State.hwProfile || { pixelRatio: 1 };

  const renderer = new THREE.WebGLRenderer({ canvas, antialias: hw.tier !== "low", alpha: true });
  renderer.setSize(w, h);
  renderer.setPixelRatio(hw.pixelRatio || Math.min(window.devicePixelRatio, 2));
  renderer.setClearColor(0x0d1117, 1);

  const scene  = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(50, w / h, 0.01, 100);
  camera.position.set(0.6, 0.4, 0.6);
  camera.lookAt(0, 0, 0);

  scene.add(new THREE.AmbientLight(0xffffff, 0.5));
  const dir = new THREE.DirectionalLight(0xffffff, 0.8);
  dir.position.set(2, 3, 2);
  scene.add(dir);

  // Grid helper
  scene.add(new THREE.GridHelper(2, 20, 0x30363d, 0x1c2333));

  const group = new THREE.Group();
  scene.add(group);

  // Simple orbit via pointer
  let dragging = false, prevX = 0, prevY = 0;
  canvas.addEventListener("pointerdown", (e) => { dragging = true; prevX = e.clientX; prevY = e.clientY; });
  window.addEventListener("pointerup",   ()  => { dragging = false; });
  canvas.addEventListener("pointermove", (e) => {
    if (!dragging) return;
    const dx = (e.clientX - prevX) * 0.005;
    const dy = (e.clientY - prevY) * 0.005;
    group.rotation.y += dx;
    group.rotation.x += dy;
    prevX = e.clientX;
    prevY = e.clientY;
  });
  canvas.addEventListener("wheel", (e) => {
    e.preventDefault();
    camera.position.multiplyScalar(e.deltaY > 0 ? 1.05 : 0.95);
  }, { passive: false });

  return { scene, camera, renderer, group };
}

function animate3D(renderer, scene, camera, group) {
  function loop() {
    requestAnimationFrame(loop);
    renderer.render(scene, camera);
  }
  loop();
}

function clearGroup(group) {
  while (group.children.length) {
    const c = group.children[0];
    if (c.geometry) c.geometry.dispose();
    if (c.material) c.material.dispose();
    group.remove(c);
  }
}

function buildDroneModel(group, exploded, segments) {
  const hw = State.hwProfile || { segments: 24 };
  segments = segments || hw.segments || 24;
  const mat = (color) => new THREE.MeshStandardMaterial({ color, metalness: 0.3, roughness: 0.6 });

  // Central body
  const body = new THREE.Mesh(
    new THREE.CylinderGeometry(0.04, 0.04, 0.025, segments),
    mat(0x3fb950)
  );
  body.userData = { name: "Body", restPos: new THREE.Vector3(0, 0, 0), explodeDir: new THREE.Vector3(0, 0, 0) };
  group.add(body);

  // Arms & motors & propellers
  const armPositions = [
    { x:  0.12, z:  0.12 },
    { x:  0.12, z: -0.12 },
    { x: -0.12, z:  0.12 },
    { x: -0.12, z: -0.12 },
  ];

  armPositions.forEach((pos, i) => {
    const color = i < 2 ? 0x00d4ff : 0xa855f7;

    // Arm
    const arm = new THREE.Mesh(
      new THREE.CylinderGeometry(0.005, 0.005, 0.17, segments),
      mat(0x58a6ff)
    );
    arm.rotation.z = Math.PI / 2;
    arm.rotation.y = Math.atan2(pos.z, pos.x);
    arm.position.set(pos.x / 2, 0, pos.z / 2);
    arm.userData = { name: "Arm " + (i + 1), restPos: arm.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.05, pos.z).normalize() };
    group.add(arm);

    // Motor
    const motor = new THREE.Mesh(
      new THREE.CylinderGeometry(0.012, 0.012, 0.02, segments),
      mat(0xa855f7)
    );
    motor.position.set(pos.x, 0.01, pos.z);
    motor.userData = { name: "Motor " + (i + 1), restPos: motor.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.15, pos.z).normalize() };
    group.add(motor);

    // Propeller (flat disc)
    const prop = new THREE.Mesh(
      new THREE.CylinderGeometry(0.06, 0.06, 0.002, segments),
      mat(color)
    );
    prop.material.transparent = true;
    prop.material.opacity = 0.5;
    prop.position.set(pos.x, 0.025, pos.z);
    prop.userData = { name: "Propeller " + (i + 1), restPos: prop.position.clone(), explodeDir: new THREE.Vector3(pos.x, 0.25, pos.z).normalize() };
    group.add(prop);
  });

  // Battery
  const batt = new THREE.Mesh(
    new THREE.BoxGeometry(0.04, 0.015, 0.06, 1, 1, 1),
    mat(0xd29922)
  );
  batt.position.set(0, -0.015, 0);
  batt.userData = { name: "Battery", restPos: batt.position.clone(), explodeDir: new THREE.Vector3(0, -0.2, 0) };
  group.add(batt);

  // Camera/sensor
  const cam = new THREE.Mesh(
    new THREE.SphereGeometry(0.01, segments, segments / 2),
    mat(0xf85149)
  );
  cam.position.set(0, -0.025, 0.03);
  cam.userData = { name: "Camera", restPos: cam.position.clone(), explodeDir: new THREE.Vector3(0, -0.3, 0.1).normalize() };
  group.add(cam);

  if (exploded) animateExplode(group, true);
}

function animateExplode(group, explode) {
  const scale = explode ? 1.0 : 0;
  group.children.forEach(child => {
    if (!child.userData || !child.userData.restPos) return;
    const rest = child.userData.restPos;
    const dir  = child.userData.explodeDir || new THREE.Vector3();
    const target = new THREE.Vector3().copy(rest).add(dir.clone().multiplyScalar(scale * 0.3));

    // Simple tween
    const start = child.position.clone();
    const startTime = performance.now();
    const duration = 800;
    function step(now) {
      const t = Math.min((now - startTime) / duration, 1);
      const ease = t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t; // ease in-out
      child.position.lerpVectors(start, target, ease);
      if (t < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  });
}

// ── Flight Simulation ────────────────────────────────────────────────
function initFlightSim() {
  const btnStart = document.getElementById("btnStartSim");
  const btnStop  = document.getElementById("btnStopSim");

  btnStart.addEventListener("click", startSim);
  btnStop.addEventListener("click", stopSim);
  document.getElementById("btnOpenTelemetry").addEventListener("click", () => {
    window.open("flight_sim.html", "_blank");
  });

  drawSimMap(); // draw initial empty map
}

function startSim() {
  if (State.simRunning) return;
  State.simRunning = true;
  State.simT       = 0;
  document.getElementById("btnStartSim").disabled = true;
  document.getElementById("btnStopSim").disabled  = false;
  document.getElementById("simDot").className      = "sim-status-dot running";
  document.getElementById("simStatusText").textContent = "Running…";
  document.getElementById("simStatus").textContent = "run";

  State.simTimer = setInterval(() => {
    State.simT += 0.5;
    updateSimTelemetry();
    drawSimMap();
    if (State.simT >= MAX_SIM_DURATION) stopSim();
  }, 500);
}

function stopSim() {
  State.simRunning = false;
  clearInterval(State.simTimer);
  document.getElementById("btnStartSim").disabled = false;
  document.getElementById("btnStopSim").disabled  = true;
  document.getElementById("simDot").className      = "sim-status-dot idle";
  document.getElementById("simStatusText").textContent = "Stopped at T+" + State.simT.toFixed(1) + "s";
  document.getElementById("simStatus").textContent = "idle";
}

function simAltitude(t) {
  return Math.min(50, 50 * (1 - Math.exp(-t / 15)));
}

function updateSimTelemetry() {
  const t   = State.simT;
  // Simple physics model for telemetry display
  const alt = simAltitude(t);
  const spd = 5 + 8 * Math.sin(t * 0.1);
  const thr = Math.max(0, Math.min(100, 60 + 20 * Math.sin(t * 0.15)));
  const bat = Math.max(0, 100 - t * 0.3);
  const tmp = 25 + t * 0.15;

  document.getElementById("telAlt").textContent     = alt.toFixed(1) + " m";
  document.getElementById("telSpeed").textContent   = spd.toFixed(1) + " m/s";
  document.getElementById("telThrottle").textContent = thr.toFixed(0) + "%";
  document.getElementById("telBattery").textContent = bat.toFixed(0) + "%";
  document.getElementById("telTemp").textContent    = tmp.toFixed(1) + "°C";
  document.getElementById("simTime").textContent    = "T+" + t.toFixed(1) + "s";
}

function drawSimMap() {
  const canvas = document.getElementById("simMapCanvas");
  const container = document.getElementById("simMapContainer");
  if (!canvas || !container) return;
  canvas.width  = container.clientWidth;
  canvas.height = container.clientHeight;
  const ctx = canvas.getContext("2d");
  const w = canvas.width;
  const h = canvas.height;

  // Dark background with grid
  ctx.fillStyle = "#0d1117";
  ctx.fillRect(0, 0, w, h);

  // Grid lines
  ctx.strokeStyle = "#1c2333";
  ctx.lineWidth = 1;
  const step = 40;
  for (let x = 0; x < w; x += step) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); }
  for (let y = 0; y < h; y += step) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); }

  // Map labels
  ctx.fillStyle = "#6e7681";
  ctx.font = "11px system-ui";
  ctx.fillText("Flight Path Map", 12, 20);

  if (!State.simRunning && State.simT === 0) {
    ctx.fillStyle = "#8b949e";
    ctx.font = "14px system-ui";
    ctx.textAlign = "center";
    ctx.fillText("Start simulation to see flight path", w / 2, h / 2);
    ctx.textAlign = "left";
    return;
  }

  // Draw flight path as a spiral/pattern
  ctx.strokeStyle = "rgba(0, 212, 255, 0.4)";
  ctx.lineWidth = 2;
  ctx.beginPath();
  const cx = w / 2, cy = h / 2;
  const maxT = State.simT;
  for (let t = 0; t <= maxT; t += 0.5) {
    const angle = t * 0.12;
    const r = 30 + t * 1.2;
    const px = cx + r * Math.cos(angle);
    const py = cy + r * Math.sin(angle);
    if (t === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();

  // Current position dot
  const angle = maxT * 0.12;
  const r = 30 + maxT * 1.2;
  const px = cx + r * Math.cos(angle);
  const py = cy + r * Math.sin(angle);

  // Glow
  const grad = ctx.createRadialGradient(px, py, 0, px, py, 15);
  grad.addColorStop(0, "rgba(0, 212, 255, 0.6)");
  grad.addColorStop(1, "rgba(0, 212, 255, 0)");
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.arc(px, py, 15, 0, Math.PI * 2);
  ctx.fill();

  // Dot
  ctx.fillStyle = "#00d4ff";
  ctx.beginPath();
  ctx.arc(px, py, 4, 0, Math.PI * 2);
  ctx.fill();

  // Label
  ctx.fillStyle = "#e6edf3";
  ctx.font = "11px system-ui";
  ctx.fillText(`Drone · Alt ${simAltitude(maxT).toFixed(1)}m`, px + 10, py - 8);
}

// ── Utility ──────────────────────────────────────────────────────────
function escHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}
